---
abstract: 'Super liberal XML parser that parses broken XML'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Liberal
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0
  Filter::Util::Call: 0
  HTML::Entities::Numbered: 0.04
  Module::Pluggable::Fast: 0.16
  XML::LibXML: 1.69_02
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://svn.coderepos.org/share/lang/perl/XML-Liberal/trunk
version: 0.22
