--- 
abstract: Super liberal XML parser that parses broken XML
author: 
  - Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XML-Liberal
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0
  HTML::Entities::Numbered: 0.04
  Module::Pluggable::Fast: 0.16
  XML::LibXML: 1.58
version: 0.19
